// src/components/Contact.vue
<script setup lang="ts">
const links = [
  {
    href: 'https://www.linkedin.com/in/luccagiovane/',
    label: 'LinkedIn',
    icon: '/icons/Linkedin-logo.svg',
    external: true,
  },
  {
    href: 'https://www.instagram.com/_luuuucca/',
    label: 'Instagram',
    icon: '/icons/Instagram-logo.svg',
    external: true,
  },
  {
    href: 'mailto:lucca.giovane.gomes@uel.br',
    label: 'Email',
    icon: '/icons/Email-icon.svg',
    external: false,
  },
]
</script>

<template>
  <section id="contact" class="contact section">
    <span class="section-title">Contact</span>
    <h2 class="section-heading">Get in touch</h2>
    <p class="contact-text">
      Feel free to reach out to me via LinkedIn or Instagram. I'm always open to
      connecting with new people and discussing exciting projects!
    </p>
    <div class="social-links">
      <a
        v-for="link in links"
        :key="link.label"
        :href="link.href"
        :target="link.external ? '_blank' : undefined"
        :rel="link.external ? 'noopener noreferrer' : undefined"
        class="social-link"
        :aria-label="link.label"
      >
        <img :src="link.icon" :alt="link.label" class="social-icon" />
        <span>{{ link.label }}</span>
      </a>
    </div>
  </section>
</template>

<style scoped>
.contact-text {
  color: var(--text-muted);
  margin-bottom: 2rem;
  max-width: 50ch;
}

.social-links {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
}

.social-link {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  background: var(--bg-elevated);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  font-size: 0.9375rem;
  font-weight: 500;
  color: var(--text);
  transition: border-color 0.2s, color 0.2s;
}

.social-link:hover {
  border-color: var(--accent);
  color: var(--accent);
}

.social-icon {
  width: 20px;
  height: 20px;
  object-fit: contain;
}
</style>

// components/Contact.tsx
import { FaLinkedinIn, FaInstagram, FaEnvelope, FaGithub } from "react-icons/fa6";
import { site } from "@/lib/data";

const socials = [
  { icon: FaLinkedinIn, href: site.linkedinUrl, label: "LinkedIn" },
  { icon: FaInstagram, href: site.instagramUrl, label: "Instagram" },
  { icon: FaEnvelope, href: `mailto:${site.email}`, label: "Email" },
  { icon: FaGithub, href: site.githubUrl, label: "GitHub" },
];

export default function Contact() {
  return (
    <section id="contact" className="bg-bg px-6 py-20">
      <div className="container mx-auto max-w-4xl text-center">
        <h2 className="mb-4 font-display text-3xl font-bold text-text">
          Let&apos;s Connect
        </h2>
        <p className="mx-auto mb-12 max-w-2xl text-subtext">
          I&apos;m happy where I am right now, but I&apos;m always open to
          connecting with fellow developers and interesting people. Got a
          question or just want to say hi? My inbox is always open.
        </p>

        <div className="mb-12 flex justify-center gap-6">
          {socials.map(({ icon: Icon, href, label }) => (
            <a
              key={label}
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={label}
              className="flex h-12 w-12 items-center justify-center rounded-full border border-border bg-surface text-xl text-subtext transition duration-300 hover:-translate-y-1 hover:border-accent hover:text-accent"
            >
              <Icon />
            </a>
          ))}
        </div>

        <a
          href={`mailto:${site.email}`}
          className="inline-block rounded-md bg-accent px-6 py-3 text-on-accent transition duration-300 hover:bg-accent-hover"
        >
          Say Hello
        </a>
      </div>
    </section>
  );
}
