// components/Footer.tsx
import { site } from "@/lib/data";

export default function Footer() {
  return (
    <footer className="border-t border-border bg-bg-alt px-6 py-8 text-center">
      <p className="mb-2 text-subtext">Developed by {site.name}</p>
      <p className="font-mono text-sm text-muted">© All rights reserved.</p>
    </footer>
  );
}

// src/components/Footer.vue
<script setup lang="ts">
</script>

<template>
  <footer class="footer">
    <p>Developed by Lucca Giovane Gomes — © All rights reserved</p>
  </footer>
</template>

<style scoped>
.footer {
  text-align: center;
  padding: 2rem 1.5rem;
  border-top: 1px solid var(--border);
  color: var(--text-muted);
  font-size: 0.875rem;
}
</style>
